// <auto-generated />
using System;
using ByteAntTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ByteAntTest.Migrations
{
    [DbContext(typeof(ByteAntTestContext))]
    partial class ByteAntTestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ByteAntTestTask.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("ByteAntTestTask.Models.Position", b =>
                {
                    b.Property<Guid>("PositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReportsToID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PositionID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("ReportsToID");

                    b.HasIndex("RoleID");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("ByteAntTestTask.Models.Role", b =>
                {
                    b.Property<Guid>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("ByteAntTestTask.Models.Position", b =>
                {
                    b.HasOne("ByteAntTestTask.Models.Employee", "Employee")
                        .WithMany("Positions")
                        .HasForeignKey("EmployeeID");

                    b.HasOne("ByteAntTestTask.Models.Position", "ReportsTo")
                        .WithMany("Subordinates")
                        .HasForeignKey("ReportsToID");

                    b.HasOne("ByteAntTestTask.Models.Role", "Role")
                        .WithMany("Positions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ReportsTo");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ByteAntTestTask.Models.Employee", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("ByteAntTestTask.Models.Position", b =>
                {
                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("ByteAntTestTask.Models.Role", b =>
                {
                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
